name: "Run CI"

on:
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.11.1
          cache: true

      - name: cppcheck installation
        run: pixi add cppcheck

      - name: configure
        run: |
          cmake -S . -B .build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=ON
          cppcheck --enable=all --disable=information -q --project=.build/compile_commands.json --suppressions-list=.cppcheck 2> cppcheck_err.txt

        shell: pixi run bash {0}

      - name: check for errors
        run: |
          if [[ -s cppcheck_err.txt ]];
          then
            cat cppcheck_err.txt
            exit 1
          fi

  tests:
    needs: pre-commit
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.11.1
          cache: true

      - run: pixi run test
